<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>CraySafe Water Quality Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #222; font-size: 11px; }
        h1 { color: #0066CC; margin: 0; font-size: 22px; }
        h2 { color: #333; font-size: 13px; margin: 18px 0 6px 0; border-bottom: 1px solid #ddd; padding-bottom: 3px; }
        .header { border-bottom: 3px solid #0066CC; padding-bottom: 12px; margin-bottom: 16px; }
        .subtitle { color: #666; font-size: 12px; margin-top: 4px; }
        .meta-table { width: 100%; margin-bottom: 14px; }
        .meta-table td { padding: 3px 0; font-size: 11px; }
        .meta-table td:first-child { width: 100px; color: #666; }
        table.data { width: 100%; border-collapse: collapse; margin-top: 6px; }
        table.data th { background: #0066CC; color: #FFF; padding: 6px; text-align: left; font-size: 10px; }
        table.data td { padding: 5px 6px; border-bottom: 1px solid #eee; font-size: 10px; }
        table.data tr:nth-child(even) { background: #f9f9f9; }
        .chart { width: 100%; margin: 6px 0 14px 0; }
        .footer { margin-top: 20px; border-top: 1px solid #ddd; padding-top: 8px; font-size: 9px; color: #888; text-align: center; }
        .summary-box { background: #f0f5fb; border-left: 3px solid #0066CC; padding: 8px 10px; margin: 6px 0; }
    </style>
</head>
<body>

<div class="header">
    <h1>CraySafe Water Quality Report</h1>
    <div class="subtitle">IoT-Based Water Quality Monitoring System</div>
</div>

<table class="meta-table">
    <tr><td>Tank:</td><td><strong>{{ $tankName }}</strong></td></tr>
    <tr><td>Period:</td><td>{{ $periodLabel }}</td></tr>
    <tr><td>Generated:</td><td>{{ $generatedAt }}</td></tr>
    <tr><td>Readings:</td><td>{{ $readingCount }}</td></tr>
</table>

<h2>Summary Statistics</h2>
<div class="summary-box">
    <strong>Temperature (°C):</strong>
    Min {{ $summary['temperature']['min'] }} ·
    Avg {{ $summary['temperature']['avg'] }} ·
    Max {{ $summary['temperature']['max'] }}
    <br>
    <strong>pH Level:</strong>
    Min {{ $summary['ph']['min'] }} ·
    Avg {{ $summary['ph']['avg'] }} ·
    Max {{ $summary['ph']['max'] }}
    <br>
    <strong>Turbidity (NTU):</strong>
    Min {{ $summary['turbidity']['min'] }} ·
    Avg {{ $summary['turbidity']['avg'] }} ·
    Max {{ $summary['turbidity']['max'] }}
</div>

<h2>Temperature Trend</h2>
<img class="chart" src="{{ $chartTempUrl }}" alt="Temperature Chart">

<h2>pH Trend</h2>
<img class="chart" src="{{ $chartPhUrl }}" alt="pH Chart">

<h2>Turbidity Trend</h2>
<img class="chart" src="{{ $chartTurbUrl }}" alt="Turbidity Chart">

<h2>Reading Log</h2>
<table class="data">
    <thead>
        <tr>
            <th>Date &amp; Time</th>
            <th>Temperature (°C)</th>
            <th>pH</th>
            <th>Turbidity (NTU)</th>
        </tr>
    </thead>
    <tbody>
        @foreach($readings as $r)
            <tr>
                <td>{{ $r['timestamp'] }}</td>
                <td>{{ $r['temperature'] }}</td>
                <td>{{ $r['ph'] }}</td>
                <td>{{ $r['turbidity'] }}</td>
            </tr>
        @endforeach
    </tbody>
</table>

<div class="footer">
    Generated by CraySafe · Capstone Project · {{ $generatedAt }}
</div>

</body>
</html>