server {
    listen 80;
    server_name _;

    root /var/www/html/public;
    index index.php index.html;

    charset utf-8;

    # Laravel's "pretty URLs"
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    # Send errors to Laravel instead of nginx's default 404 page
    error_page 404 /index.php;

    # PHP-FPM
    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_read_timeout 300;
    }

    # Block hidden files
    location ~ /\.(?!well-known).* {
        deny all;
    }
}